### ISSUE TITLE
ascii file reading crashes

### ISSUE THREAD

**Issue by hcferguson** [nmearl/pyfocal#46]
pyfocal crashed when trying to read in both of the attached ascii files.
[example_spec_ipac.txt](https://github.com/nmearl/pyfocal/files/131409/example_spec_ipac.txt)
[example_spec_ascii.txt](https://github.com/nmearl/pyfocal/files/131410/example_spec_ascii.txt)

**Comment by pllim** [comment]
@hcferguson , #48 should fix this, as far as I could test from your files. Please use the latest master and try again. Thanks!

**Comment by hcferguson** [comment]
Tried and it loads but crashes when I try to make the plot. Not sure if I've done the installation right though.

**Comment by pllim** [comment]
@hcferguson , please post the traceback here. Thanks.

**Comment by pllim** [comment]
Also, were you able to plot with the FITS test file provided by @nmearl ?

**Comment by hcferguson** [comment]
Yes.

**Comment by hcferguson** [comment]
Here's the traceback:
```
(pyf_env)Henrys-MacBook-Pro:specview hcferguson$ pyfocal
Creating from file.
WARNING: FITSFixedWarning: The WCS transformation has more axes (1) than the image it is associated with (0) [astropy.wcs.wcs]
WARNING:astropy:FITSFixedWarning: The WCS transformation has more axes (1) than the image it is associated with (0)
WARNING: UnitsWarning: 'erg/cm^2/s/Angstrom' contains multiple slashes, which is discouraged by the FITS standard [astropy.units.format.generic]
WARNING:astropy:UnitsWarning: 'erg/cm^2/s/Angstrom' contains multiple slashes, which is discouraged by the FITS standard
WARNING: UnitsWarning: The unit 'Angstrom' has been deprecated in the FITS standard. Suggested: 10**-1 nm. [astropy.units.format.utils]
WARNING:astropy:UnitsWarning: The unit 'Angstrom' has been deprecated in the FITS standard. Suggested: 10**-1 nm.
DataFactory.create_layer: None, None
(pyf_env)Henrys-MacBook-Pro:specview hcferguson$ pyfocal
Creating from file.
DataFactory.create_layer: None, None
Traceback (most recent call last):
  File "/Users/hcferguson/Documents/stsci/science_software/data_analysis_tools/sprints/specview/pyfocal/pyfocal/ui/controller.py", line 38, in <lambda>
    lambda: self.new_plot_sub_window())
  File "/Users/hcferguson/Documents/stsci/science_software/data_analysis_tools/sprints/specview/pyfocal/pyfocal/ui/controller.py", line 218, in new_plot_sub_window
    self.add_plot(data=data, window=window)
  File "/Users/hcferguson/Documents/stsci/science_software/data_analysis_tools/sprints/specview/pyfocal/pyfocal/ui/controller.py", line 249, in add_plot
    plot_container = plot_manager.new_line_plot(layer, window)
  File "/Users/hcferguson/Documents/stsci/science_software/data_analysis_tools/sprints/specview/pyfocal/pyfocal/interfaces/managers.py", line 224, in new_line_plot
    style, pen)
  File "/Users/hcferguson/Documents/stsci/science_software/data_analysis_tools/sprints/specview/pyfocal/pyfocal/interfaces/factories.py", line 146, in create_line_plot
    if plot_container.layer.uncertainty is not None:
  File "/Users/hcferguson/Documents/stsci/science_software/data_analysis_tools/sprints/specview/pyfocal/pyfocal/core/data.py", line 136, in uncertainty
    return self._source.uncertainty[self._mask]
TypeError: 'NoneType' object is not subscriptable
Abort trap: 6
```

**Comment by pllim** [comment]
@hcferguson , this should really be fixed now with #51. Please try again with latest master version and let me know if it works for you. Thank you for your patience.

**Comment by hcferguson** [comment]
Works now with both files.

**Comment by pllim** [comment]
Good to hear! :+1:
