### ISSUE TITLE
Pushing "create" before adding a model causes pyfocal to crash

### ISSUE THREAD

**Issue by hcferguson** [nmearl/pyfocal#68]
Marked an ROI on example_spec_ascii, selected a Const model, and pushed Create before pushing Add. Traceback below...

```
(pyf_env)Henrys-MacBook-Pro:specview hcferguson$ pyfocal
/Users/hcferguson/anaconda/envs/pyf_env/lib/python3.5/site-packages/astropy/units/quantity.py:822: RuntimeWarning: invalid value encountered in true_divide
  return super(Quantity, self).__truediv__(other)
/Users/hcferguson/anaconda/envs/pyf_env/lib/python3.5/site-packages/numpy/core/_methods.py:59: RuntimeWarning: Mean of empty slice.
  warnings.warn("Mean of empty slice.", RuntimeWarning)
/Users/hcferguson/anaconda/envs/pyf_env/lib/python3.5/site-packages/numpy/core/_methods.py:70: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
/Users/hcferguson/anaconda/envs/pyf_env/lib/python3.5/site-packages/numpy/core/_methods.py:82: RuntimeWarning: Degrees of freedom <= 0 for slice
  warnings.warn("Degrees of freedom <= 0 for slice", RuntimeWarning)
/Users/hcferguson/anaconda/envs/pyf_env/lib/python3.5/site-packages/numpy/core/_methods.py:94: RuntimeWarning: invalid value encountered in true_divide
  arrmean, rcount, out=arrmean, casting='unsafe', subok=False)
/Users/hcferguson/anaconda/envs/pyf_env/lib/python3.5/site-packages/numpy/core/_methods.py:116: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
void QCocoaMenu::insertNative(QCocoaMenuItem *, QCocoaMenuItem *) Menu item is already in a menu, remove it from the other menu first before inserting
void QCocoaMenu::insertNative(QCocoaMenuItem *, QCocoaMenuItem *) Menu item is already in a menu, remove it from the other menu first before inserting
void QCocoaMenu::insertNative(QCocoaMenuItem *, QCocoaMenuItem *) Menu item is already in a menu, remove it from the other menu first before inserting
void QCocoaMenu::insertNative(QCocoaMenuItem *, QCocoaMenuItem *) Menu item is already in a menu, remove it from the other menu first before inserting
void QCocoaMenu::insertNative(QCocoaMenuItem *, QCocoaMenuItem *) Menu item is already in a menu, remove it from the other menu first before inserting
void QCocoaMenu::insertNative(QCocoaMenuItem *, QCocoaMenuItem *) Menu item is already in a menu, remove it from the other menu first before inserting
void QCocoaMenu::insertNative(QCocoaMenuItem *, QCocoaMenuItem *) Menu item is already in a menu, remove it from the other menu first before inserting
void QCocoaMenu::insertNative(QCocoaMenuItem *, QCocoaMenuItem *) Menu item is already in a menu, remove it from the other menu first before inserting
void QCocoaMenu::insertNative(QCocoaMenuItem *, QCocoaMenuItem *) Menu item is already in a menu, remove it from the other menu first before inserting
void QCocoaMenu::insertNative(QCocoaMenuItem *, QCocoaMenuItem *) Menu item is already in a menu, remove it from the other menu first before inserting
void QCocoaMenu::insertNative(QCocoaMenuItem *, QCocoaMenuItem *) Menu item is already in a menu, remove it from the other menu first before inserting
void QCocoaMenu::insertNative(QCocoaMenuItem *, QCocoaMenuItem *) Menu item is already in a menu, remove it from the other menu first before inserting
void QCocoaMenu::insertNative(QCocoaMenuItem *, QCocoaMenuItem *) Menu item is already in a menu, remove it from the other menu first before inserting
void QCocoaMenu::insertNative(QCocoaMenuItem *, QCocoaMenuItem *) Menu item is already in a menu, remove it from the other menu first before inserting
void QCocoaMenu::insertNative(QCocoaMenuItem *, QCocoaMenuItem *) Menu item is already in a menu, remove it from the other menu first before inserting
Traceback (most recent call last):
  File "/Users/hcferguson/Documents/stsci/science_software/data_analysis_tools/sprints/specview/pyfocal/pyfocal/ui/controller.py", line 135, in fit_model
    fitted_model = apply_model(model, dispersion, flux, fitter_name=fitter_name)
  File "/Users/hcferguson/Documents/stsci/science_software/data_analysis_tools/sprints/specview/pyfocal/pyfocal/analysis/modeling.py", line 13, in apply_model
    result = fitter(model, x, y_init)
  File "/Users/hcferguson/anaconda/envs/pyf_env/lib/python3.5/site-packages/astropy/modeling/fitting.py", line 462, in __call__
    xtol=acc, full_output=True)
  File "/Users/hcferguson/anaconda/envs/pyf_env/lib/python3.5/site-packages/scipy/optimize/minpack.py", line 380, in leastsq
    raise TypeError('Improper input: N=%s must not exceed M=%s' % (n, m))
TypeError: Improper input: N=3 must not exceed M=0
Abort trap: 6
(pyf_env)Henrys-MacBook-Pro:specview hcferguson$ pyfocal
/Users/hcferguson/anaconda/envs/pyf_env/lib/python3.5/site-packages/astropy/units/quantity.py:822: RuntimeWarning: invalid value encountered in true_divide
  return super(Quantity, self).__truediv__(other)
/Users/hcferguson/anaconda/envs/pyf_env/lib/python3.5/site-packages/numpy/core/_methods.py:59: RuntimeWarning: Mean of empty slice.
  warnings.warn("Mean of empty slice.", RuntimeWarning)
/Users/hcferguson/anaconda/envs/pyf_env/lib/python3.5/site-packages/numpy/core/_methods.py:70: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
/Users/hcferguson/anaconda/envs/pyf_env/lib/python3.5/site-packages/numpy/core/_methods.py:82: RuntimeWarning: Degrees of freedom <= 0 for slice
  warnings.warn("Degrees of freedom <= 0 for slice", RuntimeWarning)
/Users/hcferguson/anaconda/envs/pyf_env/lib/python3.5/site-packages/numpy/core/_methods.py:94: RuntimeWarning: invalid value encountered in true_divide
  arrmean, rcount, out=arrmean, casting='unsafe', subok=False)
/Users/hcferguson/anaconda/envs/pyf_env/lib/python3.5/site-packages/numpy/core/_methods.py:116: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
WARNING: The fit may be unsuccessful; check fit_info['message'] for more information. [astropy.modeling.fitting]
WARNING:astropy:The fit may be unsuccessful; check fit_info['message'] for more information.
/Users/hcferguson/anaconda/envs/pyf_env/lib/python3.5/site-packages/astropy/units/quantity.py:822: RuntimeWarning: invalid value encountered in true_divide
  return super(Quantity, self).__truediv__(other)
(pyf_env)Henrys-MacBook-Pro:specview hcferguson$ pyfocal
/Users/hcferguson/anaconda/envs/pyf_env/lib/python3.5/site-packages/astropy/units/quantity.py:822: RuntimeWarning: invalid value encountered in true_divide
  return super(Quantity, self).__truediv__(other)
/Users/hcferguson/anaconda/envs/pyf_env/lib/python3.5/site-packages/numpy/core/_methods.py:59: RuntimeWarning: Mean of empty slice.
  warnings.warn("Mean of empty slice.", RuntimeWarning)
/Users/hcferguson/anaconda/envs/pyf_env/lib/python3.5/site-packages/numpy/core/_methods.py:70: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
/Users/hcferguson/anaconda/envs/pyf_env/lib/python3.5/site-packages/numpy/core/_methods.py:82: RuntimeWarning: Degrees of freedom <= 0 for slice
  warnings.warn("Degrees of freedom <= 0 for slice", RuntimeWarning)
/Users/hcferguson/anaconda/envs/pyf_env/lib/python3.5/site-packages/numpy/core/_methods.py:94: RuntimeWarning: invalid value encountered in true_divide
  arrmean, rcount, out=arrmean, casting='unsafe', subok=False)
/Users/hcferguson/anaconda/envs/pyf_env/lib/python3.5/site-packages/numpy/core/_methods.py:116: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
Traceback (most recent call last):
  File "/Users/hcferguson/Documents/stsci/science_software/data_analysis_tools/sprints/specview/pyfocal/pyfocal/ui/controller.py", line 286, in new_model_layer
    formula=self.viewer.current_model_formula)
  File "/Users/hcferguson/Documents/stsci/science_software/data_analysis_tools/sprints/specview/pyfocal/pyfocal/interfaces/managers.py", line 201, in get_compound_model
    result = np.sum(models) if len(models) > 1 else models[0]
IndexError: list index out of range
Abort trap: 6
(pyf_env)Henrys-MacBook-Pro:specview hcferguson$ pyfocal
/Users/hcferguson/anaconda/envs/pyf_env/lib/python3.5/site-packages/astropy/units/quantity.py:822: RuntimeWarning: invalid value encountered in true_divide
  return super(Quantity, self).__truediv__(other)
/Users/hcferguson/anaconda/envs/pyf_env/lib/python3.5/site-packages/numpy/core/_methods.py:59: RuntimeWarning: Mean of empty slice.
  warnings.warn("Mean of empty slice.", RuntimeWarning)
/Users/hcferguson/anaconda/envs/pyf_env/lib/python3.5/site-packages/numpy/core/_methods.py:70: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
/Users/hcferguson/anaconda/envs/pyf_env/lib/python3.5/site-packages/numpy/core/_methods.py:82: RuntimeWarning: Degrees of freedom <= 0 for slice
  warnings.warn("Degrees of freedom <= 0 for slice", RuntimeWarning)
/Users/hcferguson/anaconda/envs/pyf_env/lib/python3.5/site-packages/numpy/core/_methods.py:94: RuntimeWarning: invalid value encountered in true_divide
  arrmean, rcount, out=arrmean, casting='unsafe', subok=False)
/Users/hcferguson/anaconda/envs/pyf_env/lib/python3.5/site-packages/numpy/core/_methods.py:116: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
(pyf_env)Henrys-MacBook-Pro:specview hcferguson$ pyfocal
/Users/hcferguson/anaconda/envs/pyf_env/lib/python3.5/site-packages/astropy/units/quantity.py:822: RuntimeWarning: invalid value encountered in true_divide
  return super(Quantity, self).__truediv__(other)
/Users/hcferguson/anaconda/envs/pyf_env/lib/python3.5/site-packages/numpy/core/_methods.py:59: RuntimeWarning: Mean of empty slice.
  warnings.warn("Mean of empty slice.", RuntimeWarning)
/Users/hcferguson/anaconda/envs/pyf_env/lib/python3.5/site-packages/numpy/core/_methods.py:70: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
/Users/hcferguson/anaconda/envs/pyf_env/lib/python3.5/site-packages/numpy/core/_methods.py:82: RuntimeWarning: Degrees of freedom <= 0 for slice
  warnings.warn("Degrees of freedom <= 0 for slice", RuntimeWarning)
/Users/hcferguson/anaconda/envs/pyf_env/lib/python3.5/site-packages/numpy/core/_methods.py:94: RuntimeWarning: invalid value encountered in true_divide
  arrmean, rcount, out=arrmean, casting='unsafe', subok=False)
/Users/hcferguson/anaconda/envs/pyf_env/lib/python3.5/site-packages/numpy/core/_methods.py:116: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
WARNING: Model is linear in parameters; consider using linear fitting methods. [astropy.modeling.fitting]
WARNING:astropy:Model is linear in parameters; consider using linear fitting methods.
Traceback (most recent call last):
  File "/Users/hcferguson/Documents/stsci/science_software/data_analysis_tools/sprints/specview/pyfocal/pyfocal/ui/controller.py", line 135, in fit_model
    fitted_model = apply_model(model, dispersion, flux, fitter_name=fitter_name)
  File "/Users/hcferguson/Documents/stsci/science_software/data_analysis_tools/sprints/specview/pyfocal/pyfocal/analysis/modeling.py", line 13, in apply_model
    result = fitter(model, x, y_init)
  File "/Users/hcferguson/anaconda/envs/pyf_env/lib/python3.5/site-packages/astropy/modeling/fitting.py", line 462, in __call__
    xtol=acc, full_output=True)
  File "/Users/hcferguson/anaconda/envs/pyf_env/lib/python3.5/site-packages/scipy/optimize/minpack.py", line 380, in leastsq
    raise TypeError('Improper input: N=%s must not exceed M=%s' % (n, m))
TypeError: Improper input: N=1 must not exceed M=0
Abort trap: 6
(pyf_env)Henrys-MacBook-Pro:specview hcferguson$ pyfocal
/Users/hcferguson/anaconda/envs/pyf_env/lib/python3.5/site-packages/astropy/units/quantity.py:822: RuntimeWarning: invalid value encountered in true_divide
  return super(Quantity, self).__truediv__(other)
/Users/hcferguson/anaconda/envs/pyf_env/lib/python3.5/site-packages/numpy/core/_methods.py:59: RuntimeWarning: Mean of empty slice.
  warnings.warn("Mean of empty slice.", RuntimeWarning)
/Users/hcferguson/anaconda/envs/pyf_env/lib/python3.5/site-packages/numpy/core/_methods.py:70: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
/Users/hcferguson/anaconda/envs/pyf_env/lib/python3.5/site-packages/numpy/core/_methods.py:82: RuntimeWarning: Degrees of freedom <= 0 for slice
  warnings.warn("Degrees of freedom <= 0 for slice", RuntimeWarning)
/Users/hcferguson/anaconda/envs/pyf_env/lib/python3.5/site-packages/numpy/core/_methods.py:94: RuntimeWarning: invalid value encountered in true_divide
  arrmean, rcount, out=arrmean, casting='unsafe', subok=False)
/Users/hcferguson/anaconda/envs/pyf_env/lib/python3.5/site-packages/numpy/core/_methods.py:116: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
Traceback (most recent call last):
  File "/Users/hcferguson/Documents/stsci/science_software/data_analysis_tools/sprints/specview/pyfocal/pyfocal/ui/controller.py", line 286, in new_model_layer
    formula=self.viewer.current_model_formula)
  File "/Users/hcferguson/Documents/stsci/science_software/data_analysis_tools/sprints/specview/pyfocal/pyfocal/interfaces/managers.py", line 201, in get_compound_model
    result = np.sum(models) if len(models) > 1 else models[0]
IndexError: list index out of range
Abort trap: 6
(pyf_env)Henrys-MacBook-Pro:specview hcferguson$ pyfocal
/Users/hcferguson/anaconda/envs/pyf_env/lib/python3.5/site-packages/astropy/units/quantity.py:822: RuntimeWarning: invalid value encountered in true_divide
  return super(Quantity, self).__truediv__(other)
/Users/hcferguson/anaconda/envs/pyf_env/lib/python3.5/site-packages/numpy/core/_methods.py:59: RuntimeWarning: Mean of empty slice.
  warnings.warn("Mean of empty slice.", RuntimeWarning)
/Users/hcferguson/anaconda/envs/pyf_env/lib/python3.5/site-packages/numpy/core/_methods.py:70: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
/Users/hcferguson/anaconda/envs/pyf_env/lib/python3.5/site-packages/numpy/core/_methods.py:82: RuntimeWarning: Degrees of freedom <= 0 for slice
  warnings.warn("Degrees of freedom <= 0 for slice", RuntimeWarning)
/Users/hcferguson/anaconda/envs/pyf_env/lib/python3.5/site-packages/numpy/core/_methods.py:94: RuntimeWarning: invalid value encountered in true_divide
  arrmean, rcount, out=arrmean, casting='unsafe', subok=False)
/Users/hcferguson/anaconda/envs/pyf_env/lib/python3.5/site-packages/numpy/core/_methods.py:116: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
Traceback (most recent call last):
  File "/Users/hcferguson/Documents/stsci/science_software/data_analysis_tools/sprints/specview/pyfocal/pyfocal/ui/controller.py", line 286, in new_model_layer
    formula=self.viewer.current_model_formula)
  File "/Users/hcferguson/Documents/stsci/science_software/data_analysis_tools/sprints/specview/pyfocal/pyfocal/interfaces/managers.py", line 201, in get_compound_model
    result = np.sum(models) if len(models) > 1 else models[0]
IndexError: list index out of range
Abort trap: 6
```

**Comment by pllim** [comment]
Possible solutions:

1. Disable "create" button until there is a model added.
2. "Create" button silently does nothing when it is clicked without any model added.

**Comment by nmearl** [comment]
I went with 2 for now, although 1 should probably be default.
