### ISSUE TITLE
GUI crashes when I am trying to fit a model

### ISSUE THREAD

**Issue by eteq** [nmearl/pyfocal#94]
Not sure what the origin of this is, but while playing with one of the example files I experienced a hard crash.  The traceback below is what my console showed

```
WARNING: The fit may be unsuccessful; check fit_info['message'] for more information. [astropy.modeling.fitting]
WARNING:astropy:The fit may be unsuccessful; check fit_info['message'] for more information.
WARNING:root:Number of calls to function has reached maxfev = 100.
Traceback (most recent call last):
  File "/Users/etollerud/src/pyfocal/pyfocal/ui/controller.py", line 66, in <lambda>
    self.viewer.current_sub_window()))
  File "/Users/etollerud/src/pyfocal/pyfocal/ui/controller.py", line 239, in add_roi_layer
    name=layer._source.name + " Layer Slice")
  File "/Users/etollerud/src/pyfocal/pyfocal/interfaces/managers.py", line 62, in add
    new_layer = self.new(data, mask, parent, window, name)
  File "/Users/etollerud/src/pyfocal/pyfocal/interfaces/managers.py", line 57, in new
    new_layer = DataFactory.create_layer(data, mask, parent, window, name)
  File "/Users/etollerud/src/pyfocal/pyfocal/interfaces/factories.py", line 47, in create_layer
    new_layer = Layer(data, mask, parent, window, name)
  File "/Users/etollerud/src/pyfocal/pyfocal/core/data.py", line 131, in __init__
    self.units = (self._source.dispersion_unit,
AttributeError: 'Layer' object has no attribute 'dispersion_unit'
```

**Comment by pllim** [comment]
Were you using latest dev version? Where is the data file and which YAML did you use?

**Comment by eteq** [comment]
@pllim - yep, master at the time I submitted this. Data was the ``example_spec_ascii.txt``, no specific YAML (just did the simplest thing of downloading the file and loading it)

**Comment by eteq** [comment]
Oh, and this was *after* I had seen the spectrum and started trying to create models and such.  So it wasn't an on-load crash

**Comment by pllim** [comment]
It looks like @nmearl just refactored model layers in #97. Please let us know if you still see this with the dev version.

**Comment by nmearl** [comment]
Closing for now. Reopen if still any issue.
